### ISSUE TITLE
CFFI Port?

### ISSUE THREAD

**Issue by v3ss0n** [mikeboers/PyAV#129]
Would be nice this project supports CFFI as well.

**Comment by mikeboers** [comment]
Do you mean <https://cffi.readthedocs.org>?

If so, why?

**Comment by v3ss0n** [comment]
Hey , Because PyPy is 7-20x faster than python and 40% faster than nodejs.

**Comment by mikeboers** [comment]
PyAV generally already works on PyPy. It fails a few unit tests but they are either cosmetic, or due to incorrect assertions about base classes (which do not influence PyAV's behaviour).

Rewriting the whole project to use CFFI instead of Cython would yield marginal improvements to PyPy, and is very likely to yield degradation on CPython to a much larger degree.

Thanks for the idea, though!

**Comment by v3ss0n** [comment]
I understand , just a wish . Non-CFFI projects in PyPy usually have weird bugs and terrible performance. I know it will be a lot to ask for , just wanted to know if it is in your plans or no. I will test on PyPy on weekend.
 
For now  I will stick to running ffmpeg over subprocess.Thanks ;) .

**Comment by mikeboers** [comment]
I am happy to try to support PyPy, as you can see with #130 which I just opened. I should be able to add PyPy testing to Travis to make sure it stays on track.

There are a few things I was thinking of doing (with refcounting) that could break Cython's ability to work with PyPy, but I haven't done them yet, and don't know if I ever actually will.

**Comment by v3ss0n** [comment]
Thanks thats very cool! :)
