### ISSUE TITLE
Question : Using PyAV in iPython, impossible to access all frames

### ISSUE THREAD

**Issue by Celsius-J** [mikeboers/PyAV#162]
Hello,

I am willing to use iPython to track the position of an object in a movie. To do so I use Video from the PIMS library: 

> frames = pims.Video('mass_4.MOV', as_grey=True)
> frames

And I get: 

> Out[19]: <Frames>
> Source: mass_4.MOV
> Length: 9657 frames
> Frame Shape: 1280 x 720

For now everything works nice, and if I try to access to a frame from 0 to 24 it works, but if I try to access to another frame I get:

> ---------------------------------------------------------------------------
> AssertionError                            Traceback (most recent call last)
> <ipython-input-49-38df71723696> in <module>()
> ----> 1 frames[25]
> 
> /Users/Jeff/anaconda/lib/python2.7/site-packages/pims/base_frames.pyc in __getitem__(self, key)
>     161 
>     162             # else, fall back to `get_frame`
> --> 163             return self.get_frame(key if key >= 0 else _len + key)
>     164 
>     165     def __iter__(self):
> 
> /Users/Jeff/anaconda/lib/python2.7/site-packages/pims/pyav_reader.pyc in get_frame(self, j)
>     123         frame = self._current_packet[loc]  # av.VideoFrame
>     124         if frame.index != j:
> --> 125             raise AssertionError("Seeking failed to obtain the correct frame.")
>     126         result = np.asarray(frame.to_rgb().to_image())
>     127         return Frame(self.process_func(result).astype(self._dtype), frame_no=j)
> 
> AssertionError: Seeking failed to obtain the correct frame.

Do you have an idea on where the problem come from please ?

**Comment by mikeboers** [comment]
`Frame.index` is roughly [`AVCodecContext.frame_number`](https://ffmpeg.org/doxygen/2.8/structAVCodecContext.html#a9e5a25a530d01c04491216c368a1a04a), which is the index of the frame as it was decoded, not any sort of frame counter within the stream.

Without digging into how `pims` actually works, I'm saying 95% it is a bad assumption on `pims`' part.

The reason the first 24 likely work is because FFmpeg reads some frames from the front to guess at the frame rate, and so they are established with indexes that match.

**Comment by Celsius-J** [comment]
Thank you !

JF
