### ISSUE TITLE
easy way to check file integrity ?

### ISSUE THREAD

**Issue by dvasseur** [mikeboers/PyAV#183]
Is there a better/faster/less cpu intensive way to check file integrity than:
```python
container = av.open('...')
for packet in container.demux():
  for frame in packet.decode():
    continue
```

**Comment by mikeboers** [comment]
I'm not sure this falls under the scope of PyAV rather than FFmpeg/Libav, but...

What do you mean by "file integrity"? If you want to know if every frame will decode, in the absence of other data then I'm pretty sure you need to try to decode every frame. And even then, you aren't really sure that the data didn't corrupt anyways.

Maybe check-summing the files to make sure they don't change? Again, not sure what you problem domain is.

**Comment by dvasseur** [comment]
I'm using PyAV to retrieve info from downloaded media files and I would also like to check if the download was OK (file not truncated for example). I don't have any checksum available so decoding the whole file seems to be the best way (even if not perfect)

**Comment by mikeboers** [comment]
I imagine that decoding every frame is the best to do in that situation, but that will still only catch structural errors. Lots of avenues remain for corrupt data.
