### ISSUE TITLE
How to release to conda-forge

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#204]
Hey @danielballan @tacaswell,

Is there anything I can do on my end to help with assisting/tightening the release schedule re: conda-forge?

**Comment by caspervdw** [comment]
After you have uploaded the new release to Pypi, just adapt the version and SHA256 hash in [this recipe](https://github.com/conda-forge/av-feedstock/blob/master/recipe/meta.yaml). This you do via a PR so that you have the opportunity to check whether the build succeeds. You can also add yourself as maintainer in that file, which gives you push rights to the feedstock.
