### ISSUE TITLE
av_dump_format ?

### ISSUE THREAD

**Issue by wegel** [mikeboers/PyAV#306]
First of all... wow. What an amazing piece of software. Bindings are usually crap; yours is incredible! I just discovered it yesterday, and already today I got a prototype of something that would have taken me 10x as long to make using the pure C librairies. Thanks for that :)

I was wondering if its possible to use av_dump_format to get a nice output of containers, just like ffmpeg uses? I see it's mapped here:

https://github.com/mikeboers/PyAV/blob/83bf75bc801f74763990247e122eec5589ac7785/include/libavformat/avformat.pxd#L256

...but I'm not sure how to use it, or even if it's possible from within the exposed API.

Thanks again

**Comment by mikeboers** [comment]
You're very kind. 😀 

`av_dump_format` does not immediately produce nice output because it "prints" it via `av_log`, which PyAV adapts into the Python logging system.

So we would have to temporarily capture the logs, and do so only for the calling thread. It certainly isn't impossible, but not easy. (I did just add a `Container.dump_format()` method to assert this is what happens; that was easy enough on its own.)

So... I guess we refactor the log queuing stuff into a `RecordQueue` to represent everything about the record queue (instead of globals), so that we can use `PyThread_create_key` and family to manage thread-local logging queues, and a Python level context manager to capture `av_log` calls into a queue that can be turned into a list later, instead of being fed into the logging system.

**Comment by wegel** [comment]
Haha, my pleasure ;)

Seems to work good for me, although I had to use python3, as I was getting an `Import error` on `from threading import get_ident`; I think threading.get_ident() is only available in python3.

Also, it's not a problem for me but the filename seems to always be empty in the output, eg:

```
Input #0, matroska,webm, from '': <---
  Metadata:
    COMPATIBLE_BRANDS: iso6avc1mp41
    MAJOR_BRAND     : dash
    MINOR_VERSION   : 0
    ENCODER         : Lavf57.83.100
  Duration: 00:07:23.89, start: 0.000000, bitrate: 10530 kb/s
    Stream #0:0: Video: h264, yuv420p(tv, bt709, progressive), 2560x1440 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 1k tbn, 60 tbc (default)
    Metadata:
      HANDLER_NAME    : VideoHandler
      DURATION        : 00:07:23.866000000
    Stream #0:1(eng): Audio: vorbis, 44100 Hz, stereo, fltp (default)
    Metadata:
      DURATION        : 00:07:23.886000000
```

Thanks for this ;)

**Comment by mikeboers** [comment]
This is in `develop` now too.
