### ISSUE TITLE
Set hwaccel ?

### ISSUE THREAD

**Issue by wegel** [mikeboers/PyAV#307]
When using ffmpeg, we can use `-hwaccel <hwtype>` (for example with hwtype = `cuvid`) before `-i` to instruct ffmpeg to use the specified decoders, instead of the default one. In the case of cuvid, this would be `h264_cuvid`, `hevc_cuvid`, `vp9_cuvid`, etc.

This is really useful when we don't know in advance what codec a container uses, but we still want to use the hardware-accelerated decoders.

Is there a way to default to the hardware-accelerated decoders in PyAV?

Thanks!

**Comment by mikeboers** [comment]
This is not implemented currently.

Anyone have some good docs on this? All I can reasonably find about [` AVCodecContext::hwaccel_context`](https://www.ffmpeg.org/doxygen/3.3/structAVCodecContext.html#ab222f7d747dfdceff0a76999e09648c0) in 5 minutes is [this example](https://www.ffmpeg.org/doxygen/3.3/qsvdec_8c-example.html#a39).

**Comment by wegel** [comment]
I think this is what gets called when `-hwaccel cuvid` is set:

https://github.com/FFmpeg/FFmpeg/blob/fd5f4ac0813c27c34c387f00044905a859e29e37/fftools/ffmpeg_cuvid.c#L30

**Comment by rodrhern** [comment]
maybe this is vaapi example is a a good starting point.

https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/vaapi_transcode.c

to make it work I had to add `av_register_all();` at the beginning of the `main()`  (line 233 or so) and also replace

```
    ret = av_hwdevice_ctx_create(&hw_device_ctx, AV_HWDEVICE_TYPE_VAAPI, NULL, NULL, 0);
```
with 
```
    ret = av_hwdevice_ctx_create(&hw_device_ctx, AV_HWDEVICE_TYPE_VAAPI, "/dev/dri/renderD129", NULL, 0);
```
since my intel driver is not on `/dev/dri/renderD128` (default)

**Comment by rodrhern** [comment]
Hello,

@mikeboers @wegel 

I'm successfully decoding with HW Acceleration and ffmpeg-4.0 by following this example https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/hw_decode.c

I have include ffmpeg libs and made a standalone file https://github.com/rodrhern/PyAV/blob/hwdecode/av/hw_accel.pyx you can test:

```
import sys
import av

av.open_hw_accel(sys.argv[1])
```

Since I'm just starting with cython and I'm not really familiar with the code, so I'm having troubles to make it work into PyAv. Can someone give me a hand with it?

**Comment by mikeboers** [comment]
Lots of helpful stuff here! Spectacular!

So you need to pick a hwaccel type, and FFmpeg picks a device for you (or you can specify one via a string). Is there anything that enumerates devices it sees?

When I `ffmpeg -hwaccels` on my macOS here, I get `videotoolbox` which isn't one of the options I expected. Don't know what is up there.

**Comment by rodrhern** [comment]
Hello,

Yes, you choose the name of the hw acceleration: `vaapi, vdpau, etc` and then is initialized, by default you don't need to specify the device (it  can be `NULL`) https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/hw_decode.c#L51.

In my case I have installed `vdpau (/dev/dri/renderD128)` and also `vaapi (/dev/dri/renderD129)` and is kind of messy because `/dev/dri/renderD128` seems to be the default device, if I want to choose `vaapi` there is a env variable `LIBVA_DRIVER_NAME=i965` you can set for the driver name, but no for the device, so an option to specify the device address is necessary.

You can programatically list all the available devices: https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/hw_decode.c#L167

I my case this is the ffmpeg output:
```
$ ffmpeg -hwaccels
Hardware acceleration methods:
vdpau
vaapi
```

I have built ffmpeg with --enable-vaapi, but you also need to install the intel vaapi drivers
```
$ git clone https://github.com/intel/libva
$ git clone https://github.com/intel/intel-vaapi-driver
$ git clone https://github.com/intel/libva-utils
```
and then for every cloned repo in the same order
```
$ bash autogen.sh
$ ./configure --prefix=/usr
$ make
$ sudo make install
```

* I used this repo as installation reference https://github.com/pocka/docker-ffmpeg-vaapi

Regards,

**Comment by mikeboers** [comment]
Cool, although that example seems to iterate device types, not devices.

**Comment by rvillalba-novetta** [comment]
I got some version of this working for decoding. Not sure how much it may adhere to the repo's style. https://github.com/rvillalba-novetta/PyAV/tree/hwaccel

**Comment by rodrhern** [comment]
@rvillalba-novetta ,

awesome!!!, I just want to share a test I made, read a file and `pass` inside the `for` loop

```
import av
import time

video_file = sys.argv[1]
N = 10

ti = time.time()
for i in range(N):
    container = av.open(video_file)
    for frame in container.decode(video=0):
        pass
print('Software: {} [s]'.format(time.time()-ti))

hwaccel = {'device_type_name': 'vaapi', 'device': '/dev/dri/renderD129'}
ti = time.time()
for i in range(N):
    container = av.open(video_file, hwaccel=hwaccel)
    for frame in container.decode(video=0):
        pass
print('Hardware: {} [s]'.format(time.time()-ti))
```
```
$ python test_pyav.py ../streaming/small_bunny_1080p_60fps.mp4 
Software: 29.0 [s] (1 core 100% usage)
Hardware: 19.4 [s] (1 core 35% usage)
```

Also want to add that when vaapi hardware decoding (also cuvid, but haven't really tested) the frame format is `nv12` and not `yuv420p` (software decoding). For those who want to work on `RGB`, transforming from `nv12` to `RGB` is so expensive that you might loose almost all the hardware decoding saving. Transforming from `nv12`  to `yuv420p` is not that expensive

```
In [17]: frame.format.name
Out[17]: 'nv12'

In [21]: %timeit frame.reformat(format='rgb24')
6.83 ms ± 734 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [22]: %timeit frame.reformat(format='yuv420p')
821 µs ± 385 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

For me `nv12` is useful, so please don't plan force a transform to `yuv420p` :)

**Comment by notedit** [comment]
@rvillalba-novetta  hi  will you make a pr?  i will use this too.

**Comment by rvillalba-novetta** [comment]
@notedit I'm glad to, I just don't know if its close enough to what @mikeboers tends to do.

**Comment by mikeboers** [comment]
@notedit @rvillalba-novetta Honestly, this issue and the linked branch above is just as effective as a PR for me. I don't know what other influences it may have, but it doesn't make any difference in me getting it done.

I'm loving the work you're doing here, and wish I had the time to integrate it as you're doing it. Alas, I don't have that much time. I cross my fingers that I can soon.

I think I just saw a PR come in, which is great. Thanks. :)

**Comment by zaxliu** [comment]
Does anyone happen to know how to use multiple GPUs for decoding frames? Currently I use `hwaccel = {'device_type_name': 'cuda'}` but only the first GPU is used. 

I can use different GPUs in different processes by pointing `CUDA_VISIBLE_DEVICES` to only one of the GPU cards. But would like some parallelism in the same process.

**Comment by davepallot** [comment]
Any idea when this feature will be included? would be a great addition to this package.

**Comment by GiBeom-Song** [comment]
@rodrhern 
Hello, I'm a beginner of image processing. 

I want to make python OPENCV based video playback using PyAv module because `videocapture` of OPENCV function is very slow and use many CPU resources. 

So I'm trying to use Intel GPU acceleration for video decoding and formatting for OPENCV `imshow()` function. 

Fortunately, I saw and experienced your vaapi based decoding example. That's awesome! 

But, I still need converting task from `av.Videoframe` to numpy array for OPENCV `imshow` function. Although PyAv provides `to_ndarray()` function, according to my knowledge, that depends on CPU so that's very slow to display video.

So how could I approach to solve this problem?
Could you tell me the idea to use `vaapi` for converting or formatting?

**Comment by sespivak** [comment]
@GiBeom-Song 
Hi! You can see at Numba library for python for hardware accelerated calculations.
Another idea is to use opencv's ffmpeg hardware acceleration. You should set -hwaccel auto parameter for this. I don't know how yet.

**Comment by junedgar** [comment]
@GiBeom-Song 
Did you solve your problem?
I have the some problem, can you give me some advices?

**Comment by GiBeom-Song** [comment]
@junedgar 
Yes, I had solved but I didn't use a previous approach. I changed. 
the changed approach is that use h/w acceleration of FFmpeg for decoding frame and then utilize OpenGL for rendering frames decoded.

**Comment by junedgar** [comment]
@GiBeom-Song  
Thank you for your reply.
Can you show more detail for me?
I still have some confusion about this method.
Is it convenient to send you an email？

**Comment by GiBeom-Song** [comment]
@junedgar 
Sure. Please feel free to contact me but I can have some limitation to provide more detail.

**Comment by junedgar** [comment]
@GiBeom-Song  
It is very kind of you!
I can't find your email in github.
Can you show me some reference documentation for how to use OpenGL to render the decoded frames?

**Comment by GiBeom-Song** [comment]
@junedgar 
Sorry to the late reply.
I don't have an exact rendering reference or document of OpenGL. 
But I think that this Github link could be helpful for you. 
I hope you get a thing you want. 

https://gist.github.com/rcolinray/7552384

**Comment by mikeboers** [comment]
As discussed in #331, I'm no longer considering this. Thanks, everyone, for your help so far.

**Comment by nmichlo** [comment]
Hi @mikeboers,

Would there be any possibility of re-opening this? I think one of the main reasons this would be useful is reduced CPU usage rather than necessarily pure latency, like this comment: https://github.com/PyAV-Org/PyAV/pull/331#issuecomment-997205100 . I think also much of the overhead will also be reduced on modern unified memory architectures as that was one of the original closing reasons as far as I understand? https://github.com/PyAV-Org/PyAV/pull/331#issuecomment-548110744
