### ISSUE TITLE
Repackaging without transcoding

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#47]
I received this via email today.

---

I'm working on a project and i'm getting to know your PyAV library. I'm really liking it. What i would like to do is a simple video stream copy from one mkv w/ h264 video to a new mkv w/ the same stream without transcoding. I'v tried pulling packets out of the input file and just muxing them into the new file and this works for audio but not video. I've pasted my code below if there is something obvious i'm missing. Any help would be greatly appreciated.

~~~
output_video_stream = output_file.add_stream('h264', '23.976')
output_audio_stream = output_file.add_stream('ac3')

frame_count = 0

for packet in input_file.demux([s for s in (input_video_stream, input_audio_stream) if s]):
  if VERBOSE:
    print 'in', packet
  
  if packet.stream.type == 'video':
    if frame_count % 10 == 0:
      if frame_count:
        print
        print ('%03d:' % frame_count), sys.stdout.write('.'), sys.stdout.flush()
    frame_count += 1
        
  if VERBOSE:
    print 'OUT', packet
  output_file.mux(packet)
~~~

**Comment by mikeboers** [comment]
Quick link I found via the Googles: http://stackoverflow.com/a/17593502/66502

**Comment by mikeboers** [comment]
I think I've solved most of the issues with this. Needed to clear a few flags, and re-scale times. See `scratchpad/remux.py` on the `remux` branch.

**Comment by mikeboers** [comment]
This is close enough to #143 that we should consider it merged there.

**Comment by victorhcm** [comment]
I'm trying to do something similar in my application. I want to intercept the packages, while I also write them to disk (something similar to `tee`). However, I'm not able to do it. Here is a self-contained example: 

```python
import av
import pickle
import numpy as np


def write_packets(filename, packets, video_stream):
    container = av.open(filename, mode='w')
    stream = container.add_stream(
            video_stream.codec_context.name, video_stream.average_rate
    )

    stream.width = video_stream.width
    stream.height = video_stream.height
    stream.pix_fmt = video_stream.codec_context.format.name
    stream.bit_rate = video_stream.codec_context.bit_rate
    stream.options = {}

    for p in packets:
        if p.dts is not None: 
            container.mux(p)
    container.close()


out_filename = 'test.mp4'
in_container = av.open('GOPR6644.MP4')
video_stream = next(s for s in in_container.streams if s.type == 'video')
print(video_stream)

packets = [packet for packet in in_container.demux(video=0)]
write_packets(out_filename, packets, video_stream)

container2 = av.open(out_filename, mode='r')
remuxed_packets = [packet for packet in container2.demux(video=0)]
for p in remuxed_packets:
    print(p)
```

I tried to write to a .mp4 container, however it's not writing any packets as they are all 1-byte sized:

> Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 1280x720, 0 kb/s): unspecified pixel format
Consider increasing the value for the 'analyzeduration' and 'probesize' options
<av.Packet of #0, dts=0, pts=0; 1 bytes at 0x7fd09f83b868>
<av.Packet of #0, dts=1001, pts=1001; 1 bytes at 0x7fd09f83b908>
<av.Packet of #0, dts=2002, pts=2002; 1 bytes at 0x7fd09f83b9a8>
<av.Packet of #0, dts=3003, pts=3003; 1 bytes at 0x7fd09f83ba48>
...

The output file is 828 bytes only, while the original (GOPR6644.mp4) is 8,3MB, which I guess it is only the container metadata being written.

Thus, I tried to write to a .h264 file instead just to make sure, which yields a file about the same size of the original video, but it sees the packets as a single 8,2MB packet (which I think is due to some missing metadata or the lack of a container):

> Format h264 detected only with low score of 1, misdetection possible!
missing picture in access unit with size 8201183
No start code is found.
Error splitting the input into NAL units.
Stream #0: not enough frames to estimate rate; consider increasing probesize
Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
<av.Packet of #0, dts=None, pts=None; 8201183 bytes at 0x7f1f5c2fa9a8>
<av.Packet of #0, dts=None, pts=None; 0 bytes at 0x7f1f5c2faae8>

I'm not sure why the packets are not being written when I use .mp4. Am I missing something? I checked the examples, but they look similar. The only difference that comes to mind right now is the packets being decoded before being encoded and then muxed again.

**Comment by victorhcm** [comment]
It seems it was a problem specific to the .mp4 container. Using .ts (Transport Stream) we were able to make it.
