### ISSUE TITLE
av.read() exit gracefully on corrupt files?

### ISSUE THREAD

**Issue by bjuncek** [mikeboers/PyAV#485]
I'm trying to load some videos using `av.read` and I am aware that dataset contains corrupt files. Most corrupt files can get filtered out by a simple trycatch as

```
# minimal reproducible example
for d in input_files[7161:7163]:
    try:
        vr = av.open(d)
    except:
        print("Skipping file {} - might be corrupted".format(d))
```

however, on a several, the file crashes with 
```
Invalid NAL unit size (54396 > 13392).
Error splitting the input into NAL units.
Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 640x360, 750 kb/s): unspecified pixel format
```
which is not caught in the exception, but rather completely breaks the code. 
Is there a nicer way to gracefully exit or skip files upon this error? 

I could do a binary search to find the videos in question but the dataset is quite large (2M examples) and it would take hours do do it by hand.

NOTE: trying to catch it with
```        
except av.AVError:
```
fails as well.

**Comment by mikeboers** [comment]
Could you clarify what "crash" and "breaks the code" means? Does the Python interpreter exit? Or... does Python continue on as if there is no error?

**Comment by bjuncek** [comment]
There are two scenarios: 

1. if I try to catch it in the error, without exception definition so just as 
`except: some code`, the code runs (although it prints the error above, the `NAL file issue`), but the output is nonsense, and if used within a larger framework such as pytorch the error is 
```
 File "av/utils.pyx", line 27, in av.utils.AVError.__init__
TypeError: __init__() takes at least 3 positional arguments (2 given)
```

2. If I try and catch it with av.AVError, it fails immediately with 
`TypeError: __init__() takes at least 3 positional arguments (2 given)`

**Comment by mikeboers** [comment]
Interesting. It looks like the `AVError` construction is wrong. Can you post the full traceback?

**Comment by fmassa** [comment]
@mikeboers the constructor raises this error because `av.AVError` expects at least 2 arguments https://github.com/mikeboers/PyAV/blob/db30136b75e63d97cb8cb1a2e9ea4ef7ff777e2d/av/utils.pyx#L27
while in @bjuncek case, he was using PyTorch DataLoader, which wraps the exception and only passes a single argument to it, which is a string representing the full stack trace, see [here](https://github.com/pytorch/pytorch/blob/562fa55f3dfc2d3ce1cac19e3ec9dab202e06b3b/torch/utils/data/_utils/__init__.py#L18-L33) and [here](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L571-L572) for reference.

If one could make the constructor of `AVError` to accept a single argument (the message, as the first argument), then this would avoid @bjuncek errors that he mentioned. But this might be a BC-breaking change.

**Comment by jlaine** [comment]
I'm not sure I understand how PyTorch factors into this: is PyAV incorrectly constructing the AVError or is PyTorch?

Settings PyTorch aside, could we have a sample file which fails without properly raising an AVError?

**Comment by fmassa** [comment]
The problem is in PyTorch: it captures the exception message, and raises it afterwards, but only passing a single argument. I don't believe this is really a problem with PyAV, but more a limitation on how PyTorch assumes that exceptions should have their error message as the first argument

**Comment by fmassa** [comment]
Note that my last link above does not correspond to the right place anymore, here is the correct line now https://github.com/pytorch/pytorch/blob/863818e05a80b970e58a9dbce09c114ecbc6879e/torch/utils/data/dataloader.py#L608

**Comment by jlaine** [comment]
I'm sorry if I'm a bit slow here, but I don't understand the relation between PyTorch and PyAV : where is the code that uses DataLoader with PyAV?

**Comment by mikeboers** [comment]
I'm not following either, and it has been a long time. Re-open if you can show us what to change with our exceptions.
